### ISSUE TITLE
newflasher fails when there is a space in the user folder name

### ISSUE THREAD

**Issue by jisaacstone** [newflasher/newflasher#3]
Kept getting "C:\Users\Isaac" no such file or directory errors. My home folder is "C:\Users\Isaac Stone".

Just an FYI. I was able to get it to work by creating a new user account on my machine (with no space)

Cool tool and thanks for making it :+1:

**Comment by munjeni** [comment]
Thanks for reporting. I not active here and have curently no free time for fixing it, just need to add double quotes, if somebody have free time to fix that it would be cool!

**Comment by munjeni** [comment]
Fixed with https://github.com/munjeni/newflasher/commit/ff02225cefa7704883ebe37d594ee10b41adc3e7

**Comment by munjeni** [comment]
Patch above is not working, have no idea why.

**Comment by munjeni** [comment]
Can you please post your log?
