### ISSUE TITLE
Please add support Xperia 1 II XQ-AT52

### ISSUE THREAD

**Issue by rina2016** [newflasher/newflasher#30]
Please add support Xperia 1 II XQ-AT52(for Hong Kong)

ERROR: GetOverLapped_out_Result: failed with error code 1 as follows:
ファンクションが間違っています。

 - Error write! Need nBytes: 0x18 but done: 0x0
nBytes[0x0]:

 - Error writing command getvar:max-download-size!

End. You can disconnect your device when you close newflasher.exe

**Comment by rina2016** [comment]
flashtool driver installed.
but same error.

**Comment by munjeni** [comment]
Without whole log I can't help, please write full log!
