### ISSUE TITLE
Not sure if this is a bug or user error

### ISSUE THREAD

**Issue by Brandonv101** [newflasher/newflasher#36]
I am trying to flash an Xperia 1 802SO with Newflasher v35 and it seems to be giving an error:

`newflasher.exe v35 by Munjeni @ 2017/2020
Determining available free space by GetDiskFreeSpaceEx:

Available space to caller = 322159 MB Total space on current drive = 487769 MB Free space on drive = 322159 MB

Reboot mode at the end of flashing: typa 'a' for reboot to android, type 'f' for reboot to fastboot, type 's' for reboot to same mode, type 'p' for poweroff, and press ENTER. p

Optional step! Type 'y' and press ENTER if you need GordonGate flash driver, or type 'n' to skip. This creates GordonGate driver installer in the same dir with newflasher.exe! n Device path: \?\usb#vid_0fce&pid_b00b#5&1a1fdad1&0&13#{a5dcbf10-6530-11d2-901f-00c04fb951ed} Class Description: SOMC Flash Device Device Instance Id: USB\VID_0FCE&PID_B00B\5&1A1FDAD1&0&13

Optional step! Type 'y' and press ENTER if you want dump trim area, or type 'n' and press ENTER to skip. Do in mind this doesn't dump drm key since sake authentifiction is need for that! But it is recommend to have dump in case hard brick! n Product: 802SO Version: 0.4 Bootloader version: 1315-2591_X_Boot_SM8150_LA2.0_Q_115 Baseband version: 1318-2148_55.1.B.0.300 Serialno: QV72012T2W Secure: yes Loader version: XFL-SM8150-P-16 Phone ID: 0000:35512710079495 Device ID: 1F689A53 Platform ID: 300A50E1 Max download size: 104857600 Sector size: 4096 Rooting status: NOT_ROOTABLE Ufs info: SKhynix,H28U72301CMR,0003 Emmc info: FAILEmmc-info not supported Default security: ON Keystore counter: 2 Security state: oDKCbTEsCrVnLDpC7EYggwb18sCWeUIjwGnfOdBhWtY= Sake root: 2D4C8D13E459AAC3381AE995680E S1 root: Root key hash: 6C8D8435187C0ED7160856812F66743E5632EEF38B1AC8D695A91F00D35E792864812D4C8D13E459AAC3381AE995680E Slot count: 2 Current slot: a

Device is put now in flash mode.

No .sin files in partition dir... You must extract partition.zip into 'partition' folder if you want flash partition image! On 2018 and UP models you must move partition sin files to 'partition' folder if you need flash partition images!

Processing .sin files... Created ouput folder flash_session

Processing oem_other_X-FLASH-CUST-A2CD.sin - Extracting from oem_other_X-FLASH-CUST-A2CD.sin - Extracting signature oem.cms - Uploading signature C:\Users\Brand\Downloads\Newflasher\flash_session\oem.cms signature:000008b5 OKAY. - Extracting sparse chunk oem.000 - Uploading sparse chunk C:\Users\Brand\Downloads\Newflasher\flash_session\oem.000 download:0000095b OKAY. Partition: oem have slot: yes erase:oem_b OKAY. flash:oem_b OKAY. - End of oem_other_X-FLASH-CUST-A2CD.sin

Processing oem_X-FLASH-CUST-A2CD.sin - Extracting from oem_X-FLASH-CUST-A2CD.sin - Extracting signature oem.cms - Uploading signature C:\Users\Brand\Downloads\Newflasher\flash_session\oem.cms signature:000008b5 OKAY. - Extracting sparse chunk oem.000 - Uploading sparse chunk C:\Users\Brand\Downloads\Newflasher\flash_session\oem.000 download:0002d246 OKAY. Partition: oem have slot: yes erase:oem_a OKAY. flash:oem_a OKAY. - End of oem_X-FLASH-CUST-A2CD.sin

Processing .ta files... No .ta files in current dir.

Processing boot delivery...

boot_delivery.xml not exist in boot folder or no boot folder.

Set slot 'a' active.

Device is put now out of flash mode. Sent command: Sync Waiting sync to finish... .............................. error, no sync response! Closing device. Press any key to continue . . .````

The device reboots normally if I reboot manually as Newflasher does not send the power off or reboot to android commands as I am guessing this is related to the service menu. It seems like it flashes fine although if I check the service menu or Phone information in the testing menu the files do not seem to flash and VoLTE is not enabled. Not sure if Newflasher supports the 802SO but it is in flash mode since the LED is dimly lit green when holding volume down then connecting power.

**Comment by munjeni** [comment]
Since no fully confirmation I will close this issue, if you need you can reopen it.
