### ISSUE TITLE
Xperia 5 II (XQ-AS52) bootloops after flash

### ISSUE THREAD

**Issue by churchner420** [newflasher/newflasher#37]
When flashing the latest firmware with newflasher v36 on an Xperia 5 II the phone loops on the Sony logo and doesn't even get to the bootanimation. Using a different cable or usb port apparently fixed this for one user but not for me. I tried every port und three different cables but same result.

**Comment by munjeni** [comment]
Hi, I saw your post on xda but somehow after xda latest changes I'm unable to reply you. You say that you always skip partitions and userdata, I can tell you that problem with bootloop you have is related to it, you need to flash everything except persist.sin, that mean partition and userdata need to be flashed too!

**Comment by churchner420** [comment]
Ok thank you for your reply. How about the questions that newflasher asks
during the flash process? Do I need to to type y for yes anywhere? Cause I
usually type n for no to everything.
