### ISSUE TITLE
Xperia5 II Dual(XQ-AS72) after flashed looks like can't get OTA.

### ISSUE THREAD

**Issue by ExcellentHzj** [newflasher/newflasher#38]
A few days ago,I flashed my Xperia5 II Dual(XQ-AS72) to Customized SEA 58.0.A.28.25 via newflasher v36,I see https://xpericheck.com/XQ-AS72/21610788 update to 58.0.A.28.51 but I can't get this version OTA. I'm not unlocked bootloader, please help.

**Comment by munjeni** [comment]
Seems update is not released yet! See https://xpericheck.com/XQ-AS72/21610788 Further questions please continue in forum https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/
